Repository WildCodeSchool/lyon-js-sept21-p2-g3-front, pull requests merged in 2021-11, with the labels that each got.

#11 Design
  package-lock.json
  package.json
  public/media/1.png
  public/media/2.png
  public/media/Profil.jpg
  public/media/présentation P2.png
  src/App.js
  src/components/Footer.js
  src/components/IngredientList.js
  src/components/NavBar.js
  src/components/RecipeTile.js
  src/index.css
  src/pages/Home.js
  src/pages/ShoppingList.js
  tailwind.config.js
Labels: Ready for prod

#12 Shopkeepers
  .env
  package-lock.json
  package.json
  public/index.html
  public/media/Profil.jpg
  public/media/prodmen.png
  public/media/prodmen2.jpeg
  public/media/prodwoman.jpeg
  public/media/prodwoman2.jpeg
  public/media/prodwomen.jpeg
  src/App.js
  src/assets/lasagne.jpg
  src/components/Footer.js
  src/components/IngredientList.js
  src/components/NavBar.js
  src/components/RecipeTile.js
  src/index.css
  src/pages/Home.js
  src/pages/Shopkeepers.js
  src/pages/ShoppingList.js
  tailwind.config.js
Labels: Ready for validation, Ready for prod

#14 Shopkeepers
  package-lock.json
  package.json
  public/index.html
  public/media/prodmen.png
  public/media/prodmen2.jpeg
  public/media/prodwoman.jpeg
  public/media/prodwoman2.jpeg
  public/media/prodwomen.jpeg
  src/App.js
  src/pages/Shopkeepers.js
  tailwind.config.js
  yarn.lock
Labels: Ready for prod

#15 Footer
  package-lock.json
  package.json
  src/App.js
  src/components/Footer.js
  src/index.css
  src/useEventListener.js
  src/useScroll.js
  yarn.lock
Labels: Ready for validation, Ready for prod

#17 import useHistory in the NavBar component and now when the user submi…
  src/components/NavBar.js
Labels: Ready for validation, Ready for prod

#16 Add favorite
  .env
  .env.sample
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/MyFoodAPI.js
  src/components/RecipeTile.js
  src/contexts/FavoritesContexts.js
  src/pages/Favorites.js
  src/pages/Home.js
Labels: Ready for validation, Ready for prod, Conflicts

#19 Add planning
  .env
  .env.sample
  package-lock.json
  package.json
  src/App.js
  src/components/Calendar.js
  src/components/NavBar.js
  src/components/RecipeTile.js
  src/contexts/AddToPlanningContext.js
  src/index.css
  src/pages/Planning.js
  src/pages2/AddToPlanning.js
  yarn.lock
Labels: Ready for prod

#21 Shopkeepers
  package-lock.json
  public/index.html
  public/media/blanc-rouge-vin.jpeg
  public/media/boulangerie.jpeg
  public/media/boulangerie2.jpeg
  public/media/boulangerie3.jpeg
  public/media/chocolat.jpeg
  public/media/epicerie.jpeg
  public/media/i101986-cafe-nu.jpeg
  public/media/légumes.jpeg
  public/media/oeufs.jpeg
  public/media/viande.jpeg
  public/media/viennoiseries.jpeg
  public/media/vin2.jpeg
  src/pages/Shopkeepers.js
  yarn.lock
Labels: Ready for validation, Ready for prod

#22 Home random
  .vscode/launch.json
  src/App.js
  src/components/SuggestRecipies.js
  src/pages/Home.js
Labels: Ready for validation

#28 Footer
  package-lock.json
  src/App.js
  yarn.lock
Labels: Ready for validation, Ready for prod

#31 Color map
  src/index.css
  src/pages/Shopkeepers.js
Labels: Ready for validation, Ready for prod

#30 Connection sql
  package-lock.json
  src/components/IngredientList.js
  src/components/RecipeTile.js
  src/contexts/FavoritesContexts.js
  src/pages/Favorites.js
  src/pages/Planning.js
  src/pages2/AddToPlanning.js
Labels: Ready for validation, Ready for prod

#33 Delete items from list
  src/components/IngredientList.js
  src/contexts/AddToShoppingListContext.js
Labels: Ready for prod

#34 debug Home : request our API to have the suggestion of the day made b…
  src/components/SuggestRecipies.js
Labels: Ready for prod

#32 Color map
  src/pages/Shopkeepers.js
Labels: Ready for validation, Ready for prod

#36 Upgrade planning
  src/components/RecipeTile.js
  src/components/SuggestRecipies.js
  src/pages/Planning.js
  src/pages/RecipeDetails.js
  src/pages2/AddToPlanning.js
Labels: Ready for prod

#29 Link add p lanning
  package-lock.json
  public/code.txt
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/pages/Shopkeepers.js
  src/pages2/AddToPlanning.js
  yarn.lock
Labels: Ready for validation, Ready for prod
